### ISSUE TITLE
Parcels: Restore legaldesc

### ISSUE THREAD

**Issue by nickballen** [CityOfDetroit/etl-airflow#38]
The "legaldesc" field has dropped off the most recent feeds for Socrata and ArcGIS. This is critical for preparing property transfers and council resolutions--would be great to restore ASAP.

**Comment by connorlockman** [comment]
Correct me if I'm wrong @jmcbroom, but I believe that we are planning on no longer publishing the legaldesc field as migrate to ArcGIS.  The data sharing supported on ArcGIS will not allow a field with as many characters as are found in most legal descriptions. 

I sent you an email with a link to a zipped file of the legal descriptions from our most recent view and I'll speak with the team about options for publishing this info going forward!

**Comment by nickballen** [comment]
Thanks for the response. Let's close this one out given platform
limitations. Partner orgs can still get full legals from the land banks BSA
connection
